///////////////////////////////////////////////////////////
//	Copyright (C) 2020 Bosch Automotive Service Solutions INC
//  PDULogPreProcessor.cs
//  Implementation of the Class PDULogPreProcessor
//  Generated by Enterprise Architect
//  Created on:      11-Jan-2021 7:41:01 PM
//  Original author: Anoopchandra PR
//	Modification History (Latest First):
//		18-Jan-2021 9:41:01 AM	Manimaran Added PDULog Pre-processor Handling
//		11-Jan-2021 7:41:01 PM	Anoopchandra PR	Initial Version
///////////////////////////////////////////////////////////

using System;
using DataGrabomainModel;
using DataGrabDataProcessor;
using System.Text.RegularExpressions;
using System.Collections.Generic;
using System.Linq;

namespace DataGrabPreProcessor
{
    public class PDULogPreProcessor : IDataGrabPreProcessor
    {

        public PDULogPreProcessor()
        {

        }

        ~PDULogPreProcessor()
        {

        }

        /// 
        /// <param name="rawDataGrab"></param>
        public ProcessedDataGrabDataModel PreProcessDataGrab(DataGrabDataModel rawDataGrab, List<string> sidList)
        {
            try
            {
                ProcessedDataGrabDataModel processedDataGrabDataModel = new ProcessedDataGrabDataModel();
                var rawdata = rawDataGrab.RawData;
                //Remove the response string if the trace starts with response
                rawdata = rawdata.Substring(rawdata.IndexOf("==>"));
                //split the trace with ">" request symbol
                var lines = rawdata.Split(new string[] { "==>" }, StringSplitOptions.RemoveEmptyEntries);
                //iterate each line of trace
                foreach (var line in lines)
                {
                    TraceDataModel traceInfo = new TraceDataModel();
                    //split the trace with "<" response symbol
                    var traceArray = line.Trim().Split(new string[] { "<==" }, StringSplitOptions.RemoveEmptyEntries);

                    if (traceArray.Length > 0)//check array length
                    {
                        var requestArray = traceArray[0].Split(new string[] { "Rx Msg" }, StringSplitOptions.RemoveEmptyEntries);
                        //split the request and request ID
                        var requestLines = requestArray[0].Split(new string[] { "\n" }, StringSplitOptions.RemoveEmptyEntries);

                        //get the request alone
                        var request = string.Empty;
                        var reqAddress = string.Empty;
                        foreach (var requestLine in requestLines)
                        {
                            if (requestLine.Contains("[PDUAppServer]"))
                            {
                                request = request + requestLine.Substring(requestLine.IndexOf("[PDUAppServer]") + ("[PDUAppServer]").Length).Trim();
                            }
                            else
                            {
                                request = request + requestLine;
                            }
                        }
                        reqAddress = _formatAddress(request.Trim());
                        request = request.Trim().Substring(11).Trim();
                        var response = string.Empty;
                        var respAddress = string.Empty;
                        if (traceArray.Length > 1) //Assuming traceArray 0th index is always request remaings are response.check whether the response is available or not
                        {
                            for (int i = 1; i < traceArray.Length; i++)//response might have more than one
                            {
                                var resp = string.Empty;
                                var responseArray = traceArray[i].Split(new string[] { "ISO15765", ">>>>CheckForRxDataAndWrite" }, StringSplitOptions.RemoveEmptyEntries);

                                responseArray = responseArray[0].Split(new string[] { "Rx Msg", "RxTMO" }, StringSplitOptions.RemoveEmptyEntries);

                                //split the response and response ID
                                var responseLines = responseArray[0].Split(new string[] { "\n" }, StringSplitOptions.RemoveEmptyEntries);
                                foreach (var responseLine in responseLines)
                                {
                                    if (responseLine.Contains("[PDUAppServer]"))
                                    {
                                        resp = resp + responseLine.Substring(responseLine.IndexOf("[PDUAppServer]") + ("[PDUAppServer]").Length).Trim();
                                    }
                                    else
                                    {
                                        resp = resp + responseLine;
                                    }
                                }
                                respAddress = _formatAddress(resp.Trim());
                                if (i == 1)
                                {
                                    response = resp.Trim().Substring(11).Trim();//get the response.
                                }
                                else
                                {
                                    response += "+" + resp.Substring(12).Trim();//get the response
                                }
                            }   
                            //format the request and response into traceInfo object
                            traceInfo.Request = request;
                            traceInfo.EcuAddress = reqAddress;
                            traceInfo.Response = response;
                            traceInfo.TesterAddress = respAddress;  
                        }
                    }
                    if (traceInfo.EcuAddress != null)
                        processedDataGrabDataModel.TraceData.Add(traceInfo);
                }

                List<TraceDataModel> distinctTraceData = processedDataGrabDataModel.TraceData
                                                        .GroupBy(p => new { p.EcuAddress, p.Request, p.TesterAddress, p.Response, p.NegativeResponse })
                                                        .Select(g => g.First())
                                                        .ToList();
                if (distinctTraceData.Count > 0)
                {
                    processedDataGrabDataModel.TraceData = distinctTraceData;
                    processedDataGrabDataModel.VehicleData = rawDataGrab.VehicleData;
                    processedDataGrabDataModel.BusData = rawDataGrab.BusData;
                }

                return processedDataGrabDataModel;
            }
            catch (Exception ex)
            {
                throw ex;
            }
        }

        /// <summary>
        /// Format ECU Address and Tester Address from log file
        /// </summary>
        /// <param name="address"></param>
        /// <returns></returns>
        private static string _formatAddress(string address)
        {
            var ret = string.Empty;
            ret = address.Substring(0, 11).Replace("00 00 0", string.Empty).Replace(" ", string.Empty).Trim();
            return ret;
        }
    }//end PDULogPreProcessor

}//end namespace DataGrabPreProcessor